# REST Client
GET http://localhost 

###
POST http://localhost HTTP/1.1
content-type: application/json

{
    "name":"Hendry",
    "salary":"61888",
    "age":"26"
}

# curl -X POST "http://localhost" -d "Hello World"